### PR TITLE
Persian translation of the first four sections

### PR DESCRIPTION
**Pull request by pikhosh**
Index + Installing Tahoma2D, Using FFmpeg with Tahoma2D, Production Workflow, and Interface Overview
_With a little CSS for a better look for the Persian language :)_

### CODE REVIEW

**Comment by pikhosh** [comment]
@manongjohn Hi! Sorry to bother you, can I merge this?

**Comment by manongjohn** [comment]
As this is language specific, it would be ideal if another native speaker were able to review the changes, somehow.

That being said, since I don't know Farsi and don't know of any other native Farsi speakers, merge when you feel it is ready. :)

**Comment by pikhosh** [comment]
> That being said, since I don't know Farsi and don't know of any other native Farsi speakers, merge when you feel it is ready. :)

Is the Persian language going to be published after the translation of all the sections? Because the translated sections have not been published yet.

**Comment by manongjohn** [comment]
Hmm.. I think I need to do something on readthedocs.org to enable multiple languages...let me look into that.

**Comment by manongjohn** [comment]
Figured out how to enable the different languages:
image

**Pull request merged**
